### ISSUE TITLE
Alpine Linux ROS2 - ros_base foxy deps

### ISSUE THREAD

**Issue by russkel** [russkel/rosdistro#3]
### TODO:
- [ ] py3-pipenv
- [ ] superflore https://github.com/ros-infrastructure/superflore
- [ ] https://github.com/eProsima/Fast-DDS

### Unlikely to be merged:
- https://pypi.org/project/colcon-common-extensions/ - Too many dependencies. 

### Merged:
- [x] pydocstyle https://pkgs.alpinelinux.org/package/edge/testing/x86_64/py3-pydocstyle (https://github.com/alpinelinux/aports/pull/12002)
- [x] python3-lark-parser https://pkgs.alpinelinux.org/package/edge/testing/x86_64/py3-lark-parser (https://github.com/alpinelinux/aports/pull/12001)
- [x] python3-pydot https://pkgs.alpinelinux.org/package/edge/testing/x86_64/py3-pydot (https://github.com/alpinelinux/aports/pull/12000)
- [x]  python3-empy https://pkgs.alpinelinux.org/package/edge/testing/x86_64/py3-empy (https://github.com/alpinelinux/aports/pull/7635)
- [x]  python3-catkin-pkg-modules https://pkgs.alpinelinux.org/package/edge/testing/x86_64/py3-catkin-pkg-modules (https://github.com/alpinelinux/aports/pull/7641)
- [x]  assimp https://pkgs.alpinelinux.org/package/edge/testing/x86_64/assimp (https://github.com/alpinelinux/aports/pull/7762)
- [x] clang-tidy https://pkgs.alpinelinux.org/package/edge/main/x86_64/clang-extra-tools (https://gitlab.alpinelinux.org/alpine/aports/merge_requests/2249)
- [x] python3-babeltrace - https://pkgs.alpinelinux.org/package/edge/testing/x86_64/py3_babeltrace (https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/8946)
- [x] opencv - https://pkgs.alpinelinux.org/package/edge/testing/x86_64/opencv
- [x] python3-lttng -  https://pkgs.alpinelinux.org/package/edge/main/x86_64/py3-lttng https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/8952
- [x] vcstool - https://pkgs.alpinelinux.org/package/edge/testing/x86_64/vcstool - https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/8967
- [x] rosdep - https://pkgs.alpinelinux.org/package/edge/testing/x86_64/rosdep - https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/8976
- [x] python3-rospkg - https://pkgs.alpinelinux.org/package/edge/testing/x86_64/py3-rospkg - https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/8976
- [x] python3-rosdistro-modules - https://pkgs.alpinelinux.org/package/edge/testing/x86_64/py3-rosdistro - https://github.com/ros-infrastructure/rosdistro - https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/8976

### Already packaged:
- python3-qt5-bindings https://pkgs.alpinelinux.org/package/edge/community/x86_64/py3-qt5
- opengl https://pkgs.alpinelinux.org/package/edge/main/x86_64/mesa-dev
- clang-format https://pkgs.alpinelinux.org/package/edge/main/x86_64/clang
- python3-lxml https://pkgs.alpinelinux.org/package/edge/main/x86_64/py3-lxml
- python3-pkg-resources https://pkgs.alpinelinux.org/package/edge/main/x86_64/py3-setuptools
- python3-flake8 https://pkgs.alpinelinux.org/package/edge/community/x86_64/py3-flake8
- libqt5-opengl https://pkgs.alpinelinux.org/package/edge/community/x86_64/qt5-qtbase-dev
- libxml2-utils https://pkgs.alpinelinux.org/package/edge/main/x86_64/libxml2-utils
- pcre https://pkgs.alpinelinux.org/package/edge/main/x86_64/pcre-dev
- qt5-qmake https://pkgs.alpinelinux.org/package/edge/community/x86_64/qt5-qtbase-dev
- pyflakes3 https://pkgs.alpinelinux.org/package/edge/community/x86_64/py3-pyflakes
- python3-setuptools https://pkgs.alpinelinux.org/package/edge/main/x86_64/py3-setuptools
- libqt5-gui https://pkgs.alpinelinux.org/package/edge/community/x86_64/qt5-qtbase
- openssl https://pkgs.alpinelinux.org/package/edge/main/x86_64/openssl
- libxrandr https://pkgs.alpinelinux.org/package/edge/main/x86_64/libxrandr-dev
- libqt5-core https://pkgs.alpinelinux.org/package/edge/community/x86_64/qt5-qtbase
- python3-qt5-bindings https://pkgs.alpinelinux.org/package/edge/community/x86_64/py3-qt5
- libxaw https://pkgs.alpinelinux.org/package/edge/main/x86_64/libxaw
- python3-numpy https://pkgs.alpinelinux.org/package/edge/community/x86_64/py3-numpy
- python3-matplotlib https://pkgs.alpinelinux.org/package/edge/testing/x86_64/py3-matplotlib
- libx11 https://pkgs.alpinelinux.org/package/edge/main/x86_64/libx11
- libx11-dev https://pkgs.alpinelinux.org/package/edge/main/x86_64/libx11-dev
- python3-mock https://pkgs.alpinelinux.org/package/edge/main/x86_64/py3-mock
- libsqlite3-dev https://pkgs.alpinelinux.org/package/edge/main/x86_64/sqlite-dev
- git https://pkgs.alpinelinux.org/package/edge/main/x86_64/git
- spdlog https://pkgs.alpinelinux.org/package/edge/community/x86_64/spdlog-dev
- libzstd-dev https://pkgs.alpinelinux.org/package/edge/main/x86_64/zstd-dev
- libcunit-dev https://pkgs.alpinelinux.org/package/edge/main/x86_64/cunit-dev
- bullet https://pkgs.alpinelinux.org/package/edge/testing/x86_64/bullet-dev
- python3-pycodestyle https://pkgs.alpinelinux.org/package/edge/community/x86_64/py3-pycodestyle
- python3-netifaces https://pkgs.alpinelinux.org/package/edge/community/x86_64/py3-netifaces
- python3-mypy https://pkgs.alpinelinux.org/package/edge/testing/x86_64/py3-mypy
- python3-cryptography https://pkgs.alpinelinux.org/package/edge/main/x86_64/py3-cryptography
- maven https://pkgs.alpinelinux.org/package/edge/community/x86_64/maven
- java https://pkgs.alpinelinux.org/package/edge/community/x86_64/openjdk8-jre
